#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with superstitious numbers
i=0
while [ $i -lt 20 ]
do
i=$((i+1))
echo $i
case $i in
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
esac
done
